CREATE TABLE IF NOT EXISTS public.clothes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    cost real,
    times_worn integer DEFAULT 0 NOT NULL,
    is_favorite boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.clothes OWNER TO postgres;

COMMENT ON TABLE public.clothes IS 'main clothes table';

-- Policies

ALTER TABLE public.clothes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clothes_crud_own_data ON public.clothes;

CREATE POLICY clothes_crud_own_data
ON public.clothes
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.clothes TO authenticated;