CREATE TABLE IF NOT EXISTS public.tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_type text NOT NULL,
    tag_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid NOT NULL REFERENCES auth.users(id) DEFAULT SYSTEM_USER ON DELETE SET NULL
);

ALTER TABLE public.tags OWNER TO postgres;

COMMENT ON TABLE public.tags IS 'data for all tags';

-- Policies

ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tags_select_authenticated ON public.tags;

CREATE POLICY tags_select_authenticated
ON public.tags
FOR SELECT
TO authenticated
USING (true);

GRANT SELECT ON public.tags TO authenticated;