create table if not exists public.events (
  id          bigint primary key generated by default as identity,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  title       text   not null,
  description text,
  event_date  date   not null,
  start_time  time,
  end_time    time,
  location    text,
  outfit_id   bigint references public.outfits(id) on delete set null,
  created_at  timestamptz not null default now(),
  edited_at   timestamptz not null default now()
);

create index if not exists idx_events_user_date
  on public.events (user_id, event_date);

alter table public.events enable row level security;

create policy "events_select_own" on public.events
  for select using (auth.uid() = user_id);

create policy "events_insert_own" on public.events
  for insert with check (auth.uid() = user_id);

create policy "events_update_own" on public.events
  for update using (auth.uid() = user_id);

create policy "events_delete_own" on public.events
  for delete using (auth.uid() = user_id);

grant select, insert, update, delete on public.events to authenticated;