
  create table "public"."clothes" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "cost" real,
    "times_worn" integer not null default 0,
    "created_at" timestamp with time zone not null default now(),
    "edited_at" timestamp with time zone not null default now()
      );


alter table "public"."clothes" enable row level security;


  create table "public"."clothes_tags" (
    "clothes_id" bigint not null,
    "tag_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."clothes_tags" enable row level security;


  create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "tag_type" text not null,
    "tag_name" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX clothes_pkey ON public.clothes USING btree (id);

CREATE UNIQUE INDEX clothes_tags_pkey ON public.clothes_tags USING btree (clothes_id, tag_id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."clothes" add constraint "clothes_pkey" PRIMARY KEY using index "clothes_pkey";

alter table "public"."clothes_tags" add constraint "clothes_tags_pkey" PRIMARY KEY using index "clothes_tags_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."clothes" add constraint "clothes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."clothes" validate constraint "clothes_user_id_fkey";

alter table "public"."clothes_tags" add constraint "clothes_tags_clothes_id_fkey" FOREIGN KEY (clothes_id) REFERENCES public.clothes(id) ON DELETE CASCADE not valid;

alter table "public"."clothes_tags" validate constraint "clothes_tags_clothes_id_fkey";

alter table "public"."clothes_tags" add constraint "clothes_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE not valid;

alter table "public"."clothes_tags" validate constraint "clothes_tags_tag_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."clothes" to "anon";

grant insert on table "public"."clothes" to "anon";

grant references on table "public"."clothes" to "anon";

grant select on table "public"."clothes" to "anon";

grant trigger on table "public"."clothes" to "anon";

grant truncate on table "public"."clothes" to "anon";

grant update on table "public"."clothes" to "anon";

grant delete on table "public"."clothes" to "authenticated";

grant insert on table "public"."clothes" to "authenticated";

grant references on table "public"."clothes" to "authenticated";

grant select on table "public"."clothes" to "authenticated";

grant trigger on table "public"."clothes" to "authenticated";

grant truncate on table "public"."clothes" to "authenticated";

grant update on table "public"."clothes" to "authenticated";

grant delete on table "public"."clothes" to "service_role";

grant insert on table "public"."clothes" to "service_role";

grant references on table "public"."clothes" to "service_role";

grant select on table "public"."clothes" to "service_role";

grant trigger on table "public"."clothes" to "service_role";

grant truncate on table "public"."clothes" to "service_role";

grant update on table "public"."clothes" to "service_role";

grant delete on table "public"."clothes_tags" to "anon";

grant insert on table "public"."clothes_tags" to "anon";

grant references on table "public"."clothes_tags" to "anon";

grant select on table "public"."clothes_tags" to "anon";

grant trigger on table "public"."clothes_tags" to "anon";

grant truncate on table "public"."clothes_tags" to "anon";

grant update on table "public"."clothes_tags" to "anon";

grant delete on table "public"."clothes_tags" to "authenticated";

grant insert on table "public"."clothes_tags" to "authenticated";

grant references on table "public"."clothes_tags" to "authenticated";

grant select on table "public"."clothes_tags" to "authenticated";

grant trigger on table "public"."clothes_tags" to "authenticated";

grant truncate on table "public"."clothes_tags" to "authenticated";

grant update on table "public"."clothes_tags" to "authenticated";

grant delete on table "public"."clothes_tags" to "service_role";

grant insert on table "public"."clothes_tags" to "service_role";

grant references on table "public"."clothes_tags" to "service_role";

grant select on table "public"."clothes_tags" to "service_role";

grant trigger on table "public"."clothes_tags" to "service_role";

grant truncate on table "public"."clothes_tags" to "service_role";

grant update on table "public"."clothes_tags" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";


  create policy "clothes_crud_own_data"
  on "public"."clothes"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "clothes_tags_crud_own_data"
  on "public"."clothes_tags"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.clothes c
  WHERE ((c.id = clothes_tags.clothes_id) AND (c.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.clothes c
  WHERE ((c.id = clothes_tags.clothes_id) AND (c.user_id = auth.uid())))));



  create policy "tags_select_authenticated"
  on "public"."tags"
  as permissive
  for select
  to authenticated
using (true);



