CREATE TABLE IF NOT EXISTS public.ootd_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    outfit_id bigint REFERENCES public.outfits(id) ON DELETE SET NULL,
   event_id bigint REFERENCES public.events(id) ON DELETE SET NULL,
    image_type text NOT NULL,
    worn_at date NOT NULL,
    caption text,
    rating integer,
    occasion_tag_id bigint REFERENCES public.tags(id) ON DELETE SET NULL,
    weather_tag_id bigint REFERENCES public.tags(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.ootd_entries OWNER TO postgres;

COMMENT ON TABLE public.ootd_entries IS 'calendar OOTD photo log table';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ootd_entries_worn_at
  ON public.ootd_entries(user_id, worn_at DESC);

CREATE INDEX IF NOT EXISTS idx_ootd_entries_outfit_id
  ON public.ootd_entries(outfit_id);

-- CREATE INDEX IF NOT EXISTS idx_ootd_entries_event_id
--   ON public.ootd_entries(event_id);

-- Policies
ALTER TABLE public.ootd_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ootd_entries_crud_own_data ON public.ootd_entries;

CREATE POLICY ootd_entries_crud_own_data
ON public.ootd_entries
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ootd_entries TO authenticated;