CREATE TABLE IF NOT EXISTS public.outfits (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    description text,
    rating integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.outfits OWNER TO postgres;

-- Index
CREATE INDEX IF NOT EXISTS idx_outfits_created_at
  ON public.outfits(user_id, created_at DESC);

-- Policies
ALTER TABLE public.outfits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS outfits_crud_own_data ON public.outfits;

CREATE POLICY outfits_crud_own_data
ON public.outfits
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.outfits TO authenticated;